### ISSUE TITLE
How does one "read" the status led?

### ISSUE THREAD

**Issue by Bazmundi** [sparkfun/Lipo_Charger_Basic-microUSB#15]
How do I tell the difference between charged, charging and discharged using the LED?

**Comment by Bazmundi** [comment]
Cheers, I poked through the specs for the chip and had a look at the schematic.  STATUS goes HI when charged so LED goes out si!?

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I just noticed your question when browsing the issues. This is a common question when using the MCP73831T. You are correct. When the battery is charge, the LED will turn off. If you are still wondering what this stat LED does in depth, check below:

If you look at the datasheet for the LiPo USB Charger's IC controller, the LED is connected to the charge status output (STAT). This is an output to indicate the charge status which is explained in section 5.2.1 in table 5-1:

    Shutdown: Hi-Z (High-impedence mode)
    No battery present: Hi-Z
    Preconditioning: L (Low)
    Constant-Current Fast Charge: L
    Constant Voltage: L
    Charge Complete – Standby: H (High)

Since the cathode (-) of the LED is connected to the controller, setting the pin low turns the LED on; setting the pin high (or putting it in high-impedence mode) turns the LED off. From the datasheet, this unit features “AutomaticPower-Down."

Therefore, when the battery is fully **charged**, the LED should turn off and the charge IC controller should turn off.  When the battery is **discharging** to a load remotely, the LED will be off. When the **charging** a battery and it is **discharging** to a load, the LED will be on as long as the charge IC recognizes the battery as not fully charged. This can fluctuate back and forth with charging depending on if there is some small discharge with the LiPo battery/load.
